# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.15-SNAPSHOT

# Fabric API
fabric_api_version=0.155.2+26.1.2

# Mod Properties
mod_version=1.2.0
maven_group=com.tom5454.cpmflashback
archives_base_name=cpm-flashback-26.1

# CPM versions
cpm_api_version=0.6.27
cpm_mc_version=26.1
cpm_runtime_version=0.6.27a