package com.tom.cpm.client;

import com.mojang.blaze3d.platform.InputConstants;

import com.tom.cpl.gui.KeyCodes;

public class SDLKeyCodes extends KeyCodes {
	public SDLKeyCodes() {
		/** Printable keys. */
		KEY_SPACE         = InputConstants.KEY_SPACE         ;
		KEY_APOSTROPHE    = InputConstants.KEY_APOSTROPHE    ;
		KEY_COMMA         = InputConstants.KEY_COMMA         ;
		KEY_MINUS         = InputConstants.KEY_MINUS         ;
		KEY_PERIOD        = InputConstants.KEY_PERIOD        ;
		KEY_SLASH         = InputConstants.KEY_SLASH         ;
		KEY_0             = InputConstants.KEY_0             ;
		KEY_1             = InputConstants.KEY_1             ;
		KEY_2             = InputConstants.KEY_2             ;
		KEY_3             = InputConstants.KEY_3             ;
		KEY_4             = InputConstants.KEY_4             ;
		KEY_5             = InputConstants.KEY_5             ;
		KEY_6             = InputConstants.KEY_6             ;
		KEY_7             = InputConstants.KEY_7             ;
		KEY_8             = InputConstants.KEY_8             ;
		KEY_9             = InputConstants.KEY_9             ;
		KEY_SEMICOLON     = InputConstants.KEY_SEMICOLON     ;
		KEY_EQUAL         = InputConstants.KEY_EQUALS        ;
		KEY_A             = InputConstants.KEY_A             ;
		KEY_B             = InputConstants.KEY_B             ;
		KEY_C             = InputConstants.KEY_C             ;
		KEY_D             = InputConstants.KEY_D             ;
		KEY_E             = InputConstants.KEY_E             ;
		KEY_F             = InputConstants.KEY_F             ;
		KEY_G             = InputConstants.KEY_G             ;
		KEY_H             = InputConstants.KEY_H             ;
		KEY_I             = InputConstants.KEY_I             ;
		KEY_J             = InputConstants.KEY_J             ;
		KEY_K             = InputConstants.KEY_K             ;
		KEY_L             = InputConstants.KEY_L             ;
		KEY_M             = InputConstants.KEY_M             ;
		KEY_N             = InputConstants.KEY_N             ;
		KEY_O             = InputConstants.KEY_O             ;
		KEY_P             = InputConstants.KEY_P             ;
		KEY_Q             = InputConstants.KEY_Q             ;
		KEY_R             = InputConstants.KEY_R             ;
		KEY_S             = InputConstants.KEY_S             ;
		KEY_T             = InputConstants.KEY_T             ;
		KEY_U             = InputConstants.KEY_U             ;
		KEY_V             = InputConstants.KEY_V             ;
		KEY_W             = InputConstants.KEY_W             ;
		KEY_X             = InputConstants.KEY_X             ;
		KEY_Y             = InputConstants.KEY_Y             ;
		KEY_Z             = InputConstants.KEY_Z             ;
		KEY_LEFT_BRACKET  = InputConstants.KEY_LBRACKET      ;
		KEY_BACKSLASH     = InputConstants.KEY_BACKSLASH     ;
		KEY_RIGHT_BRACKET = InputConstants.KEY_RBRACKET      ;
		KEY_GRAVE_ACCENT  = InputConstants.KEY_GRAVE         ;
		KEY_WORLD_1       = 0;
		KEY_WORLD_2       = 0;

		/** Function keys. */
		KEY_ESCAPE        = InputConstants.KEY_ESCAPE        ;
		KEY_ENTER         = InputConstants.KEY_RETURN        ;
		KEY_TAB           = InputConstants.KEY_TAB           ;
		KEY_BACKSPACE     = InputConstants.KEY_BACKSPACE     ;
		KEY_INSERT        = InputConstants.KEY_INSERT        ;
		KEY_DELETE        = InputConstants.KEY_DELETE        ;
		KEY_RIGHT         = InputConstants.KEY_RIGHT         ;
		KEY_LEFT          = InputConstants.KEY_LEFT          ;
		KEY_DOWN          = InputConstants.KEY_DOWN          ;
		KEY_UP            = InputConstants.KEY_UP            ;
		KEY_PAGE_UP       = InputConstants.KEY_PAGEUP        ;
		KEY_PAGE_DOWN     = InputConstants.KEY_PAGEDOWN      ;
		KEY_HOME          = InputConstants.KEY_HOME          ;
		KEY_END           = InputConstants.KEY_END           ;
		KEY_CAPS_LOCK     = InputConstants.KEY_CAPSLOCK      ;
		KEY_SCROLL_LOCK   = InputConstants.KEY_SCROLLLOCK    ;
		KEY_NUM_LOCK      = InputConstants.KEY_NUMLOCK       ;
		KEY_PRINT_SCREEN  = InputConstants.KEY_PRINTSCREEN   ;
		KEY_PAUSE         = InputConstants.KEY_PAUSE         ;
		KEY_F1            = InputConstants.KEY_F1            ;
		KEY_F2            = InputConstants.KEY_F2            ;
		KEY_F3            = InputConstants.KEY_F3            ;
		KEY_F4            = InputConstants.KEY_F4            ;
		KEY_F5            = InputConstants.KEY_F5            ;
		KEY_F6            = InputConstants.KEY_F6            ;
		KEY_F7            = InputConstants.KEY_F7            ;
		KEY_F8            = InputConstants.KEY_F8            ;
		KEY_F9            = InputConstants.KEY_F9            ;
		KEY_F10           = InputConstants.KEY_F10           ;
		KEY_F11           = InputConstants.KEY_F11           ;
		KEY_F12           = InputConstants.KEY_F12           ;
		KEY_F13           = InputConstants.KEY_F13           ;
		KEY_F14           = InputConstants.KEY_F14           ;
		KEY_F15           = InputConstants.KEY_F15           ;
		KEY_F16           = InputConstants.KEY_F16           ;
		KEY_F17           = InputConstants.KEY_F17           ;
		KEY_F18           = InputConstants.KEY_F18           ;
		KEY_F19           = InputConstants.KEY_F19           ;
		KEY_F20           = InputConstants.KEY_F20           ;
		KEY_F21           = InputConstants.KEY_F21           ;
		KEY_F22           = InputConstants.KEY_F22           ;
		KEY_F23           = InputConstants.KEY_F23           ;
		KEY_F24           = InputConstants.KEY_F24           ;
		KEY_F25           = 0;
		KEY_KP_0          = InputConstants.KEY_NUMPAD0       ;
		KEY_KP_1          = InputConstants.KEY_NUMPAD1       ;
		KEY_KP_2          = InputConstants.KEY_NUMPAD2       ;
		KEY_KP_3          = InputConstants.KEY_NUMPAD3       ;
		KEY_KP_4          = InputConstants.KEY_NUMPAD4       ;
		KEY_KP_5          = InputConstants.KEY_NUMPAD5       ;
		KEY_KP_6          = InputConstants.KEY_NUMPAD6       ;
		KEY_KP_7          = InputConstants.KEY_NUMPAD7       ;
		KEY_KP_8          = InputConstants.KEY_NUMPAD8       ;
		KEY_KP_9          = InputConstants.KEY_NUMPAD9       ;
		KEY_KP_DECIMAL    = InputConstants.KEY_NUMPADCOMMA   ;
		KEY_KP_DIVIDE     = 84;
		KEY_KP_MULTIPLY   = InputConstants.KEY_MULTIPLY      ;
		KEY_KP_SUBTRACT   = 86;
		KEY_KP_ADD        = InputConstants.KEY_ADD           ;
		KEY_KP_ENTER      = InputConstants.KEY_NUMPADENTER   ;
		KEY_KP_EQUAL      = InputConstants.KEY_NUMPADEQUALS  ;
		KEY_LEFT_SHIFT    = InputConstants.KEY_LSHIFT        ;
		KEY_LEFT_CONTROL  = InputConstants.KEY_LCONTROL      ;
		KEY_LEFT_ALT      = InputConstants.KEY_LALT          ;
		KEY_LEFT_SUPER    = InputConstants.KEY_LGUI          ;
		KEY_RIGHT_SHIFT   = InputConstants.KEY_RSHIFT        ;
		KEY_RIGHT_CONTROL = InputConstants.KEY_RCONTROL      ;
		KEY_RIGHT_ALT     = InputConstants.KEY_RALT          ;
		KEY_RIGHT_SUPER   = InputConstants.KEY_RGUI          ;
		KEY_MENU          = 118;
		KEY_LAST          = 512;
	}
}
